config/routes.rb
Hotline::Application.routes.draw do
  
  
  root "questions#index"
  
  resources :questions
  resources :responses
  
  get "users/create"
  match "/auth/google_oauth2/callback" => "sessions#create", via: [:get, :post]
  match "/signout" => "sessions#destroy", :as => :signout, via: [:get, :post]

  get 'users/:id' => "users#show", as: "user"
  post 'questions/:id/edit' => "questions#update", as: "update_question"

  post "responses/mark_answer", as: "mark_answer"
  get 'tags/:tag', to: 'questions#index', as: :tag

  post "questions/search", as: "search"
  get "search/:search" => "questions#result", as: "result"

  get "search" => "questions#search"

  get "users" => "users#all_users", as: "users"

end

app/models/question.rb
class Question < ActiveRecord::Base
  validates_presence_of :title, :description, :tag_list
  
  validate :file_size_validation

  has_many :responses
  belongs_to :user
  acts_as_taggable_on :tags

  has_attached_file :file_avatar, :default_url => "/files/:style/missing.doc"
  validates_attachment_content_type :file_avatar, :content_type => ['application/zip', /application/, /text/]
  
  private 
  def file_size_validation
    return if file_avatar.blank?
    errors[:file_avatar] << "should be less than 1MB" if file_avatar.size > 1.megabytes
  end



end

app/models/response.rb
class Response < ActiveRecord::Base
  validates_presence_of :response

  validate :file_size_validation
  
  belongs_to :question
  belongs_to :user

  has_attached_file :file_avatar, :default_url => "/files/:style/missing.doc"
  validates_attachment_content_type :file_avatar, :content_type => ['application/zip', /application/, /text/]

  private 
  def file_size_validation
    return if file_avatar.blank?
    errors[:file_avatar] << "should be less than 1MB" if file_avatar.size > 1.megabytes
  end

end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :responses
  has_many :questions

  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  helper_method :current_user

  private
  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end
  
end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
  def index
    if params[:tag]
      @questions = Question.tagged_with(params[:tag])
    else
      @questions = Question.all
    end
      @questions = @questions.paginate(:page => params[:page], :per_page => 15).order('id DESC')
  end

  def show
    @question = Question.find_by_id(params[:id])
    @responses = Response.where("question_id = '#{params[:id]}'").order(correct: :desc)
    @response = Response.new
  end

  def new
    if current_user
      @question = Question.new
    else 
      redirect_to root_path
    end
  end


    def edit
    if current_user
      @question = Question.find(params[:id])
    else 
      redirect_to root_path
    end
  end

    def update
      @question = Question.find(params[:id])
      @question.title = params[:question][:title]
      @question.description = params[:question][:description]
      @question.save
      redirect_to question_path(@question)
    end

  def create
    tag_list = params[:question][:tag_list]
    @question = Question.new(question_params)
    @question.tag_list = tag_list
    @question.user = current_user
    if @question.save
      flash[:notice] = "Successfully Posted!"
      redirect_to question_path(@question)
    else
      flash[:errors] = @question.errors.full_messages
      render 'new'
    end
  end

  def search 
    if params[:search] == nil
      redirect_to :back
    else 
      redirect_to("/search/" + params[:search])
    end
  end

  def result 
    @results = Question.where(["title ILIKE ? OR description ILIKE ?", "%#{params[:search]}%", "%#{params[:search]}%"]);
    render 'search'
  end

  def tag_cloud
    tag_list = Question.tag_list_counts_on(:tags, :limit => 5, :order => "count desc")
  end
  
  private
  def question_params
    params.require(:question).permit(:hangout_link, :title, :description, :file_avatar)
  end



end

  

app/controllers/responses_controller.rb
class ResponsesController < ApplicationController
  def create
    @response = Response.new(response_params)
    @response.question = Question.find(params[:question_id].to_i)
    @response.user = current_user
    if params[:response][:response].include? "<script>"
      flash[:errors] = ["Sorry there was an error with your reply. Please try again!"]
      redirect_to question_path(@response.question)
    else    
      if @response.save
        flash[:notice] = "Successfully Replied!"
        redirect_to question_path(@response.question)
      else
        flash[:errors] = @response.errors.full_messages
        redirect_to question_path(@response.question)      
      end
    end
  end

  def mark_answer 
    new_correct_response = params[:response]
    current_question = params[:question_id]
    current_correct = Response.where(correct: true, question_id: current_question)
    if new_correct_response
      if current_correct.first
        current_correct.first.correct = false
        current_correct.first.save
      end
      @new_correct = Response.find(new_correct_response)
      @new_correct.correct = true
      @new_correct.save
      redirect_to question_path(current_question)
    else 
      redirect_to root_path
    end
  end
  
  private
  def response_params
    params.require(:response).permit(:response, :file_avatar, :hangout_link) 
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def create
    auth = request.env["omniauth.auth"]
    user = User.where(:provider => auth["provider"], :uid => auth["uid"]).first_or_initialize(
      :first_name => auth["info"]["first_name"],
      :last_name => auth["info"]["last_name"],
      :name => auth["info"]["name"],
      :email => auth["info"]["email"],
      :refresh_token => auth["credentials"]["refresh_token"],
      :access_token => auth["credentials"]["token"],
      :expires => auth["credentials"]["expires_at"],
      :image => auth["info"]["image"]
    )
    url = session[:return_to] || root_path
    session[:return_to] = nil
    url = root_path if url.eql?('/logout')

    if user.save
      session[:user_id] = user.id
      notice = "Signed in!"
      logger.debug "URL to redirect to: #{url}"
      redirect_to url, :notice => notice
    else
      raise "Failed to login"
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to root_url, :notice => "Signed out!"
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def create
    User.create(user_params)
  end

  def show
    @profile_user = User.find(params[:id])
 	end

 	def all_users
 		@users = User.all
 	end


  private
  def user_params
    params.require(:user).permit(:name, :email, :first_name, :last_name, :image, :provider, :uid, :refresh_token, :access_token, :expires)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/questions_helper.rb
module QuestionsHelper

  def render_question_description
    des = @question.description.split(' ')
    i = 0
    link_extract = []
    while i < des.length
      if des[i].start_with?('http')
        link_extract << "<a target='_blank' href='#{des[i]}'>#{des[i]}</a>"
      else 
        link_extract << des[i]
      end
      i += 1
    end 
    return link_extract.join(' ').html_safe
  end

  def render_question_hangout_link
    des = @question.hangout_link.split(' ')
    i = 0
    link_extract = []
    while i < des.length
      if des[i].start_with?('http')
        link_extract << "<a target='_blank' href='#{des[i]}'>#{des[i]}</a>"
      else 
        link_extract << des[i]
      end
      i += 1
    end 
    return link_extract.join(' ').html_safe
  end

  def render_response(response)
    res = response.response.split(' ')
    i = 0
    link_extract = []
    while i < res.length
      if res[i].start_with?('http')
        link_extract << "<a target='_blank' href='#{res[i]}'>#{res[i]}</a>"
      else 
        link_extract << res[i]
      end
      i += 1
    end 
    return link_extract.join(' ').html_safe
  end
end

app/helpers/responses_helper.rb
module ResponsesHelper
	 def render_response_hangout_link(response)
    des = response.hangout_link.split(' ')
    i = 0
    link_extract = []
    while i < des.length
      if des[i].start_with?('http')
        link_extract << "<a target='_blank' href='#{des[i]}'>#{des[i]}</a>"
      else 
        link_extract << des[i]
      end
      i += 1
    end 
    return link_extract.join(' ').html_safe
  end
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
  	<title>askadev</title>
  	<%= favicon_link_tag 'favicon.ico' %>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
		<link href="//netdna.bootstrapcdn.com/font-awesome/4.0.3/css/font-awesome.css" rel="stylesheet">

 		<%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
    <title><%= content_for?(:title) ? yield(:title) : "foundation-rails" %></title>
    <%= javascript_include_tag "vendor/modernizr" %>
  	<%= javascript_include_tag "application", "data-turbolinks-track" => true %>
    <%= csrf_meta_tags %>
  </head>

  <body>

	<div class="contain-to-grid sticky" data-options="sticky_on: large" >
		<nav class="top-bar" data-topbar>
		  <ul class="title-area">
		    <li class="name">
		      <h1><a href="<%= root_path %>"><%=image_tag('logo.gif')%></a></h1>
		    </li>
		    <li class="toggle-topbar menu-icon"><a href="#">Menu</a></li>
		  </ul>

		  <section class="top-bar-section">
		    
		    <!-- Right Nav Section -->
		    <ul class="right">
		      <% if current_user %>
			      <li class="has-dropdown topbar-field">
							<a href="">Hi <%= current_user.first_name %> </a>
			        <ul class="dropdown">
			          <li><a href='/users/<%= current_user.id %>'> My Profile </a></li>
								<li> <a href='<%= signout_path %>'> Sign Out </a> </li>
			        </ul>
			      </li>
		      <% else %>
		      	<li><%= link_to image_tag('g.png') + "Sign in with google", '/auth/google_oauth2', {class: 'gsign-in topbar-field'} %></li>
		      <% end %>
		    </ul>

		    <div class='right extra-btn topbar-field'>
			  	<a href="#" class='about' data-reveal-id="myModal" data-reveal>About</a>
		      <% if current_user %>
						<a href='<%= new_question_path%>' class='button'> Ask Question </a>
					<% end %>
			  </div>
		    <!-- Left Nav Section -->
	    <ul class="left">
				<li class="has-form topbar-field">
				  <div class="row collapse">
				  <span class='search'>
				    <%= form_tag search_path, method: :post do |f| %>
					    <div class="large-8 small-8 columns">
					      <%= text_field_tag 'search', nil, placeholder: 'Discover...', required: :required %>
					    </div>
					    <div class="large-4 small-4 columns">
								<%= submit_tag("Search", {class: 'active button expand'}) %>
					    </div>
				    <% end %>
				    </span>
				  </div>
				</li>    
			</ul>

		  </section>
		</nav>
	</div>



	<div class='container'>
		<div class="row">
	  	<div class="small-9 large-9 columns"> 
	  		<section class='main-body'>
					<% if flash[:notice] %>
	  				<div data-alert class="alert-box success radius">
							<%= flash[:notice] %>
  						<a href="#" class="close">&times;</a>
						</div>
					<% end %>
					<section class='inner-tab'>
						<a href='<%= root_path %>'> Questions </a>
						<a href='<%= users_path %>'> Users </a>
						<a> Live Sessions </a><sup>COMING SOON</sup>
					</section>
	  		</section>
	  	</div>
		</div>

		<div class="row">
			<section class='main-inner'>
	  		<%= yield %> 				
	  	</section>
	  </div>
	</div>



	<div id="myModal" class="reveal-modal" data-reveal>
  		<h2 style='text-align: center'> 24 hr Developer Hotline </h2> 
  	<section class='modal-container'>
	  	<section class='about-info'>
	  		<h4>Ask a Question</h4>
	  		<p> Got a question about your code? Stuck on something? Record a quick video where you describe the issue.</p>
	  	</section>
	  	<section class='about-info'>
	  		<h4>Get an Answer</h4>
	  		<p>A friendly coder will help you, by posting a video response. You can also pair with them with live video chat.</p>
	  	</section>
	  	<section class='about-info'>
	  		<h4>Be part of the Community</h4>
	  		<p> Your question and answer becomes an online resource for others learning to code.
	 </p>
	  	</section>
	  </section>
  	<a class="close-reveal-modal">&#215;</a>
	</div>


		<script type="text/javascript" src="https://apis.google.com/js/platform.js"></script>
		<script type="text/javascript">
		  gapi.hangout.render('placeholder-div3', {
		    'render': 'createhangout',
		    'hangout_type': 'onair',
		    'widget_size': 175
		  });
		</script>	
  </body>
</html>

app/views/questions/edit.html.erb
	<%= form_for(@question) do |f| %>
		
		<%= f.text_field :title %> <br>
		<%= f.text_area :description %> <br>

		<%= f.submit("Save", {class: 'active button'}) %>

	<% end %>

app/views/questions/index.html.erb
<div class="medium-8 columns">
	<section class='home-feed'>


		<ul id="questions">
			<% if params[:tag] %>
				<h6>Tags matching "<%= params[:tag] %>"</h6><br>
			<% end %>
		<% @questions.each do |question| %>
			<li> 
				<a href ="questions/<%= question.id %>">  <%= question.title %> </a>  <br>
		<% question.tag_list.each do |tag| %>
			  <span class="radius secondary label"><%= raw link_to tag, tag_path(tag) %></span>
		<% end %>
		
		<span class='username'><a href='<%= user_path(question.user)%>'> <%= question.user.name %> </a></span> <br>


				<span class='username'> <%= timeago_tag question.created_at, :nojs => true, :limit => 10.days.ago %> </span> <br>
			</li>
		<% end %> 
		</ul>
	</section>

  	<div>
				<%= will_paginate @questions %>
		</div>


</div>

<div class="medium-4 columns">
	<section class='right-barindex'>
		<div id="tag_cloud">
  		<% tag_cloud Question.tag_counts, %w{s m l} do |tag, css_class| %>
    	<span class="radius secondary label"><%= link_to tag.name, tag_path(tag.name), class: css_class %></span>
  <% end %>
		</div>
	</section>
</div>

app/views/questions/new.html.erb
<div class="medium-8 columns">
	<%= form_for @question, :html => { :multipart => true } do |f| %>

		<% if flash[:errors] %>
			<div data-alert class="alert-box warning radius">
				<%=flash[:errors].first %>
  			<a href="#" class="close">&times;</a>
			</div>
		<% end %>

		<div id="placeholder-div3"></div> <br><br>
		<%= f.text_field :title, placeholder: 'Title' %> <br>
		<%= f.text_field :hangout_link, placeholder: "Paste the 'Embed Video URL' from the Hangout window in 'Links'" %> <br>
		<%= f.text_area :description, placeholder: 'Description' %> <br>
		
		<%= f.text_field :tag_list, {id: "widget1"} %><br><br>

		<label> Attach one or more files as a zip file.</label>
	
	  <%= f.file_field :file_avatar %><br>

		<%= f.submit("Ask", {class: 'active button'}) %>

	<% end %>
</div>

<div class="medium-4 columns">
	<section class='right-bar'>

	<div class="arrow"> How to Post A Video Question  <i class="fa fa-caret-square-o-down"></i></div> 
	<div id="box1" class="box">
	

		<p>1. Open your troublesome code in your preferred text editor.</p>
 	

		<p>2. Click the Hangouts on Air button. A new window will open. Press the big green icon, then Join Now and set up your hangout. Write askadev in the Name of the hangout, then start the hangout. </p>


		<p>3. Select the green share icon and choose the window for your text editor. This is what will be recorded.</p>

		<p><%= image_tag('Screenshare.png', size: "50")%></p>

		
		<p>4. Save the link to your recording before you begin. It's very important you remember this step, or we won't be able to retrieve your video once you've finished! To save it, click the Links icon in the bottom right corner, and copy the embed video URL. Paste the link into the link field on your Question page.</p>


		<p><%=image_tag('Links.png', size: "80")%></p>

		<p>5. When you're ready press Start Broadcast! Remember to speak through the problem you have.</p>


		<p><%=image_tag('Start.png', size: "150")%></p>

		<p>6. Finished your question? Press Stop broadcast. </p>

		<p><%=image_tag('Stop.png', size: "150")%></p>
		</div>

		


		

app/views/questions/search.html.erb
	<section class='home-feed'>
		<ul>
		<h6>Search results for "<%= params[:search] %>"</h6><br>
		<% @results.each do |result| %>
			<li> 
				<a href ="<%= question_path(result) %>">  <%= result.title %> </a>  <br>
				<% result.tag_list.each do |tag| %>
					  <span class="radius secondary label"><%= raw link_to tag, tag_path(tag) %></span>
				<% end %>
		
		<span class='username'><a href='<%= user_path(result.user)%>'> <%= result.user.name %> </a></span> <br>
				<span class='username'> <%= timeago_tag result.created_at, :nojs => true, :limit => 10.days.ago %> </span> <br>
			</li>
		<% end %> 
		</ul>
</section>

app/views/questions/show.html.erb
<div class="medium-8 columns">

	<section class='question'>
		
		<% if current_user && current_user.questions.where(id: params[:id]).any? %>
			<%= link_to "edit", edit_question_path(@question)  %>
		<% end %>

		<h2><%= @question.title %> </h2><br>
		<p> <%= render_question_description %> </p>
		<% if !@question.hangout_link.nil? %>
			<p><%= render_question_hangout_link %></p>
		<% end %>

		<% @question.tag_list.each do |tag| %>
				  <span class="radius secondary label"><%= raw link_to tag, tag_path(tag) %></span>
		<% end %>
		<br>
		
		<% if @question.file_avatar_file_name %>
			<br><i class="fa fa-paperclip"></i><a href='<%= @question.file_avatar.url %>'> <%=@question.file_avatar_file_name%></a><br>
		<% end %>
		<span class='username'><a href='<%= user_path(@question.user)%>'> <%= @question.user.name %> </a></span> <br>
		<span class='username'> <%= timeago_tag @question.created_at, :nojs => true, :limit => 10.days.ago %> </span>

			<section class='hangout'>
		<% if current_user %>
				<h4> Know the answer? </h4>
				<div id="placeholder-div3"></div>
		<% end %>
			</section>
	</section>


	<section class='response-feed'>
		<%= form_tag mark_answer_path, id: 'mark-answer', method: :post do |f| %>
			<% @responses.each do |response| %>
				<li>
					<aside>
						<% if current_user && current_user.questions.where(id: params[:id]).any? %>
							<% if response.correct == true %>
								<%= image_tag('correct.png', size: "32", class: "correct-ans", 'data-id' => "#{response.id}", 'data-question' => "#{@question.id}")%>
							<% else %>
								<%= image_tag('disabled_correct.png', size: "32", class: "correct-ans", 'data-id' => "#{response.id}", 'data-question' => "#{@question.id}")%>
							<% end %>
						<% end %>
					</aside>

					<section>	
				<% if response.correct == true %>
					<h5> Best Answer </h5> 
				<% end %> 
						<p><%= render_response(response) %> </p>
						<% if !response.hangout_link.nil? %>
							<br><p><%= render_response_hangout_link(response) %></p>
						<% end %>
						<a href='<%= response.file_avatar.url %>'><%= response.file_avatar_file_name %></a>
						<span class='username'><a href='<%= user_path(response.user)%>'><%= response.user.name %></a></span> <br>
						<span class='username'><%= timeago_tag response.created_at, :nojs => true, :limit => 10.days.ago %></span>
					</section>

				</li>
			<% end %>
		<% end %>
	</section>

	<% if current_user %>
		<section class='reply'>
			<%= form_for @response, :html => { :multipart => true } do |f| %>
				<% if flash[:errors] %>
					<div data-alert class="alert-box warning radius">
						<%= flash[:errors].first %> 
  					<a href="#" class="close">&times;</a>
					</div>
				<% end %>	
				
				<%= f.text_area(:response, placeholder: 'Make their life easier...')%>
				<%= f.text_field(:hangout_link, placeholder: "Paste the 'Embed Video URL' from the Hangout window in 'Links'")%>
				<%= f.file_field(:file_avatar) %>
				<input type='hidden' name='question_id' value='<%=@question.id%>'>  
				<%= f.submit("Reply", {class: 'active button'}) %>
			<% end %>
		</section>
	<% end %>

</div>
	<div class="medium-4 columns">
	<section class='right-bar'>

	<div class="arrow2"> How to Record an Answer <i class="fa fa-caret-square-o-down"></i></div>
	 <div id="box2" class="box2">

		<p>1. Download the attached code and open it in your preferred text editor, ready to work on.</p>

		<p>2. If you can solve their problem, click the Hangouts on Air button. A new window will open. Press the big green icon, then Join Now and set up your hangout. Give it the same Name as the question you're answering.</p>

		<p>3. Select the green share icon and choose the window which you will be working from, for example your text editor. This is what will be recorded.</p>

		<p><%= image_tag('Screenshare.png', size: "50")%></p>

		<p>4. Save the link to your recording before you begin. It's very important you remember this step, or we won't be able to retrieve your video once you've finished! To save it, click the Links icon in the bottom right corner, and copy the embed video URL. Paste the link in a reply to the question on askadev.</p>

		<p><%=image_tag('Links.png', size: "80")%></p>
      
		<p>5. When you're ready press Start Broadcast! Remember to speak aloud your thoughts.  </p>

		<p><%=image_tag('Start.png', size: "150")%></p>

		<p>6. Finished answering? Press Stop broadcast. Your video will be automatically embedded on the site, to be viewed by the askadev community.</p>

		<p><%=image_tag('Stop.png', size: "150")%></p>
		</div>

	</section>
	
</div>

app/views/users/all_users.html.erb
<section class='home-feed'>
	<% @users.each do |user| %>
		<section class='all-user'>
			<a href='<%=user_path(user)%>'> <img src= "<%= user.image %> "> </a>
			<h5><a href='<%=user_path(user)%>'><%= user.name %></a></h5>
		</section>
	<% end %>
</section>

app/views/users/show.html.erb
<div class="row">
  <div class="large-4 columns">
		<section class='profile-image'>
			<img src= "<%= @profile_user.image %> ">
			<h4> <strong><%= @profile_user.name %></strong></h4>
			<p> Joined on <%= @profile_user.created_at.strftime("%B %d, %Y") %></p>
		</section>
  </div>
  <div class="large-8 columns">
  	<section class='profile-questions'>
			<h3> Questions Asked</h3>
				<% @profile_user.questions.each do |question| %>
					<li><a href='<%= question_path(question) %>'><%= question.title %></a></li>
				<% end %>
			
		</section>
  </div>
</div>